version: "3.8"

services:

  postgres:
    image: postgres
    restart: always
    container_name: biblioteca_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: AUTECO_DB

volumes:
  pgdata:

# Run the following command to start the services
# docker-compose up -d